src/Entity/Order.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="orders")
 */
class Order
{
    const STATUS_NEW = 'new';
    const STATUS_PAID = 'paid';

    protected static $statuses = [
        self::STATUS_NEW => 'Новый',
        self::STATUS_PAID => 'Оплачен',
    ];

    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue()
     * @var int
     */
    protected $id;

    /**
     * @ORM\Column(type="json")
     * @var array
     */
    protected $products;

    /**
     * @ORM\Column(type="string")
     * @var string
     */
    protected $status;

    public function __construct()
    {
        $this->products = [];
        $this->status = self::STATUS_NEW;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return array
     */
    public function getProducts(): array
    {
        return $this->products;
    }

    /**
     * @param int $id
     *
     * @return Order
     */
    public function addProduct(int $id): Order
    {
        if (!in_array($id, $this->products)) {
            $this->products[] = $id;
        }

        return $this;
    }

    /**
     * @param int $id
     *
     * @return Order
     */
    public function removeProduct(int $id): Order
    {
        if (in_array($id, $this->products)) {
            unset($this->products[array_search($id, $this->products)]);
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     *
     * @return Order
     */
    public function setStatus(string $status): Order
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return string
     */
    public function getStatusName(): string
    {
        return self::$statuses[$this->status];
    }
}

src/Controller/OrderController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Order;
use App\Entity\Product;
use Doctrine\ORM\ORMException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class OrderController extends AbstractController
{
    /**
     * @return Response
     * @throws \Exception
     */
    public function create(): Response
    {
        $session = $this->container['session'];
        $cart = $session->get('cart', []);

        if (empty($cart)) {
            return $this->json(['error' => 'В корзине нет товаров'], Response::HTTP_BAD_REQUEST);
        }

        $order = new Order();

        foreach ($cart as $productId) {
            $order->addProduct((int)$productId);
        }

        try {
            $em = $this->container['em'];
            $em->persist($order);
            $em->flush();
            $session->remove('cart');
        } catch (ORMException $e) {
            $this->container['logger']->error($e->getMessage(), ['trace' => $e->getTraceAsString()]);

            return $this->json(['error' => 'Не удалось создать заказ'], Response::HTTP_BAD_REQUEST);
        }

        return $this->json(['orderId' => $order->getId()]);
    }

    /**
     * @param int $id
     *
     * @return Response
     * @throws \Exception
     */
    public function get(int $id): Response
    {
        try {
            $order = $this->loadOrder($id);
        } catch (NotFoundHttpException $e) {
            return new Response($e->getMessage(), Response::HTTP_NOT_FOUND);
        }

        $products = $this->container['em']->getRepository(Product::class)
            ->findBy(['id' => $order->getProducts()]);

        return $this->render('order/view.html.twig', [
            'order' => $order,
            'products' => $products,
        ]);
    }

    /**
     * @param int $id
     *
     * @return Response
     */
    public function pay(int $id): Response
    {
        try {
            $order = $this->loadOrder($id);
        } catch (NotFoundHttpException $e) {
            return $this->json(['error' => $e->getMessage()], Response::HTTP_NOT_FOUND);
        }

        if ($order->getStatus() === Order::STATUS_PAID) {
            return $this->json(['error' => 'Заказ уже оплачен'], Response::HTTP_BAD_REQUEST);
        }

        if (!$this->container['payment_service']->payOrder()) {
            return $this->json(['error' => 'Платежная система недоступна'], Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        $order->setStatus(Order::STATUS_PAID);
        $this->container['em']->flush();

        return $this->json(['status' => $order->getStatusName()]);
    }

    /**
     * @param int $id
     *
     * @return Order
     */
    protected function loadOrder(int $id): Order
    {
        $em = $this->container['em'];
        /** @var Order $order */
        $order = $em->getRepository(Order::class)->find($id);

        if (!$order) {
            throw new NotFoundHttpException('Заказ не найден');
        }

        return $order;
    }
}

templates/order/view.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <div class="container">
        <h1>Заказ <span class="badge {% if order.status is constant('STATUS_NEW', order) %}badge-primary{% else %}badge-success{% endif %}" id="status">{{ order.statusName }}</span></h1>
        <div class="row">
            {% for product in products %}
                <div class="col-sm-3">
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">Цена: {{ product.price }}₽</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            {% if order.status is constant('STATUS_NEW', order) %}
                <a href="/orders/{{ order.id }}/pay" class="btn btn-primary pay-order">Оплатить</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block custom_js %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).on('click', '.pay-order', function (e) {
                e.preventDefault();
                var button = $(this),
                    status = $('#status');

                $.post(button.attr('href'), function (data) {
                    if (data.status) {
                        button.remove();
                        status.removeClass('badge-primary');
                        status.addClass('badge-success');
                        status.html(data.status);
                    }
                })
                    .fail(function (data) {
                        if (data.error) {
                            alert(data.error);
                        } else {
                            alert('Не удалось оплатить заказ')
                        }
                    });
            });
        });
    </script>
{% endblock custom_js %}